# This file was generated by GoReleaser. DO NOT EDIT.
cask "pm" do
  name "pm"
  desc ""
  homepage "https://github.com/blurfx/homebrew-tap"
  version "0.2.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"

  on_macos do
    on_intel do
      url "https://github.com/blurfx/pm/releases/download/v#{version}/pm_Darwin_x86_64.tar.gz"
      sha256 "447bed3068c250f1b37c975800c5068522190061b40a3d7f52b3ddb40572ae77"
    end
    on_arm do
      url "https://github.com/blurfx/pm/releases/download/v#{version}/pm_Darwin_arm64.tar.gz"
      sha256 "f13ea1f51b96cba9c70baabf7c92f4482fd81e14a61484de65f0a11b6a41fd35"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blurfx/pm/releases/download/v#{version}/pm_Linux_x86_64.tar.gz"
      sha256 "3f49e90558086fed6de7bb820c350291aa3ebeacfd30abd9c1940353b0544f3c"
    end
    on_arm do
      url "https://github.com/blurfx/pm/releases/download/v#{version}/pm_Linux_arm64.tar.gz"
      sha256 "0c7257701e51a82d667a24e0555e42e5496083195ea205c1fb1d077d1cc943e7"
    end
  end

  # No zap stanza required
end
