# This file was generated by GoReleaser. DO NOT EDIT.
cask "pm" do
  desc ""
  homepage "https://github.com/blurfx/homebrew-tap"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pm"

  on_macos do
    on_intel do
      url "https://github.com/blurfx/pm/releases/download/v0.2.0/pm_Darwin_x86_64.tar.gz"
      sha256 "d6278e40a0ceb473ca2420fe7482a7e7b9c661320758a9236575069b88ad1692"
    end
    on_arm do
      url "https://github.com/blurfx/pm/releases/download/v0.2.0/pm_Darwin_arm64.tar.gz"
      sha256 "0dda971cf6d6cab7df7f07cbd9119b9f3764709411e12e0b151bc90243fac38f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blurfx/pm/releases/download/v0.2.0/pm_Linux_x86_64.tar.gz"
      sha256 "390778610713e7af327f0b434a8923be8dfacf0a97c1601b8713496904bc4afe"
    end
    on_arm do
      url "https://github.com/blurfx/pm/releases/download/v0.2.0/pm_Linux_arm64.tar.gz"
      sha256 "daa478c23f35f63fc752feb0808f97d6457a390ef5afcd15faa2c6e7e4ffa735"
    end
  end

  # No zap stanza required
end
