# This file was generated by GoReleaser. DO NOT EDIT.
cask "unegg" do
  name "unegg"
  desc ""
  homepage "https://github.com/blurfx/homebrew-tap"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unegg"

  on_macos do
    on_intel do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Darwin_x86_64.tar.gz"
      sha256 "1db7f893abee4438a7ca3980d70fe4825ec3153b0f442a51442db205a07f2635"
    end
    on_arm do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Darwin_arm64.tar.gz"
      sha256 "b3d86e1f293c378465899d0ed6c5deded3b208200f9be9d2fd4f6ab34e421977"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Linux_x86_64.tar.gz"
      sha256 "5f5afd308b366b6c6826985b6401126b5673e712057e0f3aac9ae097db5fd2be"
    end
    on_arm do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Linux_arm64.tar.gz"
      sha256 "d14ce6707227ffbefc8e948547cedb410e74496ae30923fa2639a3eb6ba2b8b2"
    end
  end

  # No zap stanza required
end
