# This file was generated by GoReleaser. DO NOT EDIT.
cask "unegg" do
  name "unegg"
  desc ""
  homepage "https://github.com/blurfx/homebrew-tap"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unegg"

  on_macos do
    on_intel do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Darwin_x86_64.tar.gz"
      sha256 "7af5e811ba586bc1f823ecde0d971d4cf071a1a230069a17c12cd48ccd19f1ea"
    end
    on_arm do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Darwin_arm64.tar.gz"
      sha256 "99a91b8b3b081a28aae15cbad6ab7003c2f7034949d9cdfc470f41a073dffaed"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Linux_x86_64.tar.gz"
      sha256 "a47753e7023a139c1ced7d3b8a2eeccf151954f767c308bf5eadef3450440deb"
    end
    on_arm do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Linux_arm64.tar.gz"
      sha256 "5600ae3d90c6de961d9f47676682d18be34474c5d0da01bb7d07fa7e5bc5662e"
    end
  end

  # No zap stanza required
end
