# This file was generated by GoReleaser. DO NOT EDIT.
cask "unegg" do
  name "unegg"
  desc ""
  homepage "https://github.com/blurfx/homebrew-tap"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unegg"

  on_macos do
    on_intel do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Darwin_x86_64.tar.gz"
      sha256 "88304624558d03041ea5b5dd73289de7d892283ac7985fd151db4a517274189f"
    end
    on_arm do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Darwin_arm64.tar.gz"
      sha256 "7689b23c4e38f940aae4c7a527498314241b2f886ad7de4b352c8c42e3586da4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Linux_x86_64.tar.gz"
      sha256 "d83d980a3a8cb9800fdab6b3b10a96a8aeeb127139e41a6b3de572177d8d1196"
    end
    on_arm do
      url "https://github.com/blurfx/unegg/releases/download/v#{version}/unegg_Linux_arm64.tar.gz"
      sha256 "8a130fb1fb25e6204f66283c9ffb0cc45e79d6532758f4269bf0e53497847ee1"
    end
  end

  # No zap stanza required
end
